events {}

http {
  proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=imgcache:10m max_size=1g inactive=60m use_temp_path=off;

  server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
      proxy_pass http://minio:9000; # MinIO Service im Docker-Netz
      proxy_set_header Host $host;

      proxy_cache imgcache;
      proxy_cache_valid 200 302 10m;
      proxy_cache_valid 404 1m;
      add_header X-Cache-Status $upstream_cache_status;
    }
  }
}
